spring:
  application:
    name: dayJava
  
  # Thymeleaf Configuration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    check-template-location: true
    
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:dayjavadb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
    whitelabel:
      enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 